services:
  - type: web
    name: espacoon
    runtime: node
    repo: https://github.com/p3rtub4d00/Espa-oOn
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ASAAS_API_KEY
        sync: false
      - key: ASAAS_ENV
        value: production
      - key: ASAAS_WEBHOOK_TOKEN
        sync: false
