services:
  - type: web
    name: espacoon
    runtime: static
    repo: https://github.com/p3rtub4d00/Espa-oOn
    branch: main
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    autoDeploy: true
