import { useEffect, useState } from 'react'
import { api } from '../data/api'
import { clubToday } from '../../shared/visit-history'
import './rescheduling.css'
export function RescheduleHistory({ reservation }) {
  return <>{reservation.rescheduleRequest && <p className="reschedule-note">Solicitação de remarcação: {({pending:'aguardando aprovação do proprietário',approved:'aprovada',rejected:'recusada'})[reservation.rescheduleRequest.status]} · {reservation.rescheduleRequest.dateISO?.split('-').reverse().join('/')} {reservation.rescheduleRequest.ownerMessage || ''}</p>}{(reservation.reschedules || []).map(change=><div className="reschedule-record" key={change.id}><strong>Remarcação aprovada</strong><p>{change.fromDateISO?.split('-').reverse().join('/')} → {change.dateISO?.split('-').reverse().join('/')} às {change.startTime}</p><small>Adicional combinado: R$ {Number(change.extraFee || 0).toFixed(2)} · {change.feeStatus==='received'?'recebimento registrado':change.extraFee>0?'recebimento pendente':'sem adicional'}. O contrato original permanece preservado.</small></div>)}</>
}
export default function RescheduleForm({reservation, owner=false, cpf, onSaved, onClose}) {
  const pending=owner && reservation.rescheduleRequest?.status==='pending' ? reservation.rescheduleRequest : null
  const [month,setMonth]=useState(clubToday().slice(0,7)),[date,setDate]=useState(pending?.dateISO || ''),[time,setTime]=useState(pending?.startTime || reservation.startTime || '08:00'),[reason,setReason]=useState(''),[fee,setFee]=useState('0'),[agreed,setAgreed]=useState(false),[settings,setSettings]=useState(null),[availability,setAvailability]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState('')
  useEffect(()=>{let alive=true;Promise.all([api.getSettings(),api.getAvailability()]).then(([s,a])=>{if(alive){setSettings(s);setAvailability(a)}}).catch(e=>{if(alive)setError(e.message)});return()=>{alive=false}},[])
  const unavailable=new Set([...(availability?.reservedDates||[]),...(availability?.pendingDates||[]),...(availability?.blockedDates||[]),reservation.dateISO])
  const days=[]
  if(/^\d{4}-\d{2}$/.test(month)){const last=new Date(Number(month.slice(0,4)),Number(month.slice(5)),0).getDate();for(let i=1;i<=last;i++){const iso=month+'-'+String(i).padStart(2,'0');if(iso>=clubToday()&&!unavailable.has(iso))days.push(iso)}}
  const times=settings?.rentalStartTimes?.[reservation.period] || ['08:00']
  const submit=async(decision)=>{setError('');setBusy(true);try{const payload={dateISO:date,startTime:time,reason,extraFee:fee,agreed,decision,ownerMessage:reason,requestId:pending?.id};const saved=owner?await api.respondReschedule(reservation.id,payload):await api.requestReschedule({...payload,code:reservation.id,cpf});onSaved(saved)}catch(e){setError(e.message)}finally{setBusy(false)}}
  const message=['Olá! Sobre a reserva '+reservation.id, 'Nova data: '+date.split('-').reverse().join('/')+' às '+time,'Valor adicional proposto: R$ '+Number(fee||0).toFixed(2),'Você concorda com a remarcação e esse valor?'].join('\n')
  let phone=String(reservation.customer?.phone||'').replace(/\D/g,'');if(phone&&!phone.startsWith('55'))phone='55'+phone
  return <section className="reschedule-form"><h3>{pending?'Revisar solicitação':'Remarcar reserva'}</h3><p>A data original continua reservada até a aprovação. A nova data pode ser ocupada enquanto o pedido aguarda resposta.</p>
    {pending?<p className="reschedule-note">Pedido do cliente: {pending.dateISO.split('-').reverse().join('/')} às {pending.startTime}<br/>Motivo: {pending.reason}</p>:<><label>Mês desejado<input type="month" min={clubToday().slice(0,7)} value={month} onChange={e=>{setMonth(e.target.value);setDate('')}} /></label><label>Nova data disponível<select value={date} onChange={e=>setDate(e.target.value)} disabled={!availability}><option value="">{availability?'Escolha uma data':'Consultando disponibilidade...'}</option>{days.map(day=><option key={day} value={day}>{day.split('-').reverse().join('/')}</option>)}</select></label><label>Horário de entrada<select value={time} onChange={e=>setTime(e.target.value)}>{[...new Set([...times,time])].map(t=><option key={t}>{t}</option>)}</select></label></>}
    <label>{pending?'Resposta / motivo da recusa':'Motivo da remarcação'}<textarea maxLength={500} value={reason} onChange={e=>setReason(e.target.value)} /></label>
    {owner&&<><label>Valor adicional combinado (R$)<input type="number" min="0" step="0.01" value={fee} onChange={e=>setFee(e.target.value)} /></label><small>Não há cobrança automática. Combine o adicional com o cliente antes de aprovar; o pagamento original não será alterado.</small>{phone&&<a className="reschedule-whatsapp" target="_blank" rel="noopener noreferrer" href={'https://wa.me/'+phone+'?text='+encodeURIComponent(message)}>Combinar com o cliente no WhatsApp</a>}<label className="reschedule-check"><input type="checkbox" checked={agreed} onChange={e=>setAgreed(e.target.checked)} />O cliente concordou com a nova data e o eventual valor adicional.</label></>}
    {error&&<p role="alert" className="lookup-error">{error}</p>}<div className="reschedule-actions"><button disabled={busy||!date||!settings||(owner&&!agreed)||(!owner&&reason.trim().length<3)} onClick={()=>submit('approve')}>{busy?'Salvando...':owner?'Aprovar remarcação':'Solicitar remarcação'}</button>{pending&&<button disabled={busy||reason.trim().length<3} onClick={()=>submit('reject')}>Recusar solicitação</button>}<button disabled={busy} onClick={onClose}>Voltar</button></div>
  </section>
}
